####################################################################################
# Script: txt_to_csv.3.R
# Author: Wenting Lyu
# Notes: this script helps convert the txt file to cxv file for later analysis.
#         please note that there are two ways to run the script.
#         1) interactive way. 
#         First, run script in console by typing: source("txt_to_csv.3.R") 
#         Second, select the txt file generated by lipidSearch from the poping window
#         Third
#         2) straight way.
#         First comment the interactive way by selecting the interactive block in the code 
#               (comment shortcut: command+shift+c)
#         Second run the code line by line or as a whole
#####################################################################################
rm(list=ls())

list.of.packages <- c("tidyverse", "readr", "magrittr")
need.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[, "Package"])]
if(length(need.packages)) install.packages(need.packages)

# path for storing converted files
dir <- "converted"
if(!file.exists(dir)){
  dir.create(dir)
} 

# Suppress the package messages
lapply(list.of.packages, function(x) 
  suppressMessages(require(x, character.only = TRUE, quietly = TRUE)))

files <- read_table(file.choose(), skip_empty_rows = TRUE)
job_name <- names(files) %>% str_split(., "\t") 
file_name <- job_name[[1]][2] %>% paste(., ".csv", sep = "")


index <- sapply(files, function(x) which(str_detect(x, "Rej"))) 
contents <- files %>% filter(row_number() >= index)

# convert data format into data.frame
data <- apply(contents, 1, function(x) str_split(x, "\t") %>% unlist) %>% t() %>% as.data.frame()
colnames(data) <- unlist(data[1, ])
data <- data[-1, ]

sample_neg <- sapply(files, function(x) length(which(str_detect(x, "neg"))))
sample_pos <- sapply(files, function(x) length(which(str_detect(x, "pos"))))

# Verify the sample size info are correct.
message("Reminder: Is your sample negative tests are ", sample_neg, " times?")
message("Reminder: Is your sample positive tests are ", sample_pos, " times?")


# reconstruct the data columns and store it into the file
####################################################################################
# selecting the columns we want for analysis
cols_data <- data %>%
  select(contains("ARatio"), contains("APValue"), contains("MainIon"),
         contains("MainGrade"), contains("MainArea"),
         -contains("NMA"), -contains("Score")
  )
#unorder_name <- paste("unordered.", file_name, sep="")
#name1 <- paste(dir, "/", unorder_name, sep = "", collapse = "")
#### unordered data            
uncleaned.data <- data %>% select(1:9) %>% bind_cols(cols_data) #%>% write_csv(., name1)

#### ordered ones 
order.sample.names <- uncleaned.data %>% 
  select(matches("\\[(c|s.*)\\]")) %>%    
  colnames() %>% 
  str_sort(., numeric=TRUE) 

unorder_data <- uncleaned.data[- which(names(uncleaned.data) %in% order.sample.names)]
name2 <- paste(dir, "/", file_name, sep = "", collapse = "")
ordered_data <- uncleaned.data[, order.sample.names] %>% 
  bind_cols(unorder_data, .) %>%
  arrange(Class, LipidMolec) %>% 
  write_csv(., name2)
